version: "3.8"
services:
  ralphee:
    image: ubuntu:latest
    volumes:
      - ralphee_data:/home
      - ./:/home/ws_dev/src/haql-rover
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    command: bash -c "
        . /home/ws_dev/src/haql-rover/setup.bash
      "
volumes:
  ralphee_data:
